// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.communication.rooms.implementation.models;

import com.azure.core.annotation.Fluent;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.HashMap;
import java.util.Map;

/** The ProblemDetails model. */
@Fluent
public final class ProblemDetails {
    /*
     * The type property.
     */
    @JsonProperty(value = "type")
    private String type;

    /*
     * The title property.
     */
    @JsonProperty(value = "title")
    private String title;

    /*
     * The status property.
     */
    @JsonProperty(value = "status")
    private Integer status;

    /*
     * The detail property.
     */
    @JsonProperty(value = "detail")
    private String detail;

    /*
     * The instance property.
     */
    @JsonProperty(value = "instance")
    private String instance;

    /*
     * Dictionary of <any>
     */
    @JsonIgnore private Map<String, Object> additionalProperties;

    /**
     * Get the type property: The type property.
     *
     * @return the type value.
     */
    public String getType() {
        return this.type;
    }

    /**
     * Set the type property: The type property.
     *
     * @param type the type value to set.
     * @return the ProblemDetails object itself.
     */
    public ProblemDetails setType(String type) {
        this.type = type;
        return this;
    }

    /**
     * Get the title property: The title property.
     *
     * @return the title value.
     */
    public String getTitle() {
        return this.title;
    }

    /**
     * Set the title property: The title property.
     *
     * @param title the title value to set.
     * @return the ProblemDetails object itself.
     */
    public ProblemDetails setTitle(String title) {
        this.title = title;
        return this;
    }

    /**
     * Get the status property: The status property.
     *
     * @return the status value.
     */
    public Integer getStatus() {
        return this.status;
    }

    /**
     * Set the status property: The status property.
     *
     * @param status the status value to set.
     * @return the ProblemDetails object itself.
     */
    public ProblemDetails setStatus(Integer status) {
        this.status = status;
        return this;
    }

    /**
     * Get the detail property: The detail property.
     *
     * @return the detail value.
     */
    public String getDetail() {
        return this.detail;
    }

    /**
     * Set the detail property: The detail property.
     *
     * @param detail the detail value to set.
     * @return the ProblemDetails object itself.
     */
    public ProblemDetails setDetail(String detail) {
        this.detail = detail;
        return this;
    }

    /**
     * Get the instance property: The instance property.
     *
     * @return the instance value.
     */
    public String getInstance() {
        return this.instance;
    }

    /**
     * Set the instance property: The instance property.
     *
     * @param instance the instance value to set.
     * @return the ProblemDetails object itself.
     */
    public ProblemDetails setInstance(String instance) {
        this.instance = instance;
        return this;
    }

    /**
     * Get the additionalProperties property: Dictionary of &lt;any&gt;.
     *
     * @return the additionalProperties value.
     */
    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    /**
     * Set the additionalProperties property: Dictionary of &lt;any&gt;.
     *
     * @param additionalProperties the additionalProperties value to set.
     * @return the ProblemDetails object itself.
     */
    public ProblemDetails setAdditionalProperties(Map<String, Object> additionalProperties) {
        this.additionalProperties = additionalProperties;
        return this;
    }

    @JsonAnySetter
    void setAdditionalProperties(String key, Object value) {
        if (additionalProperties == null) {
            additionalProperties = new HashMap<>();
        }
        additionalProperties.put(key, value);
    }
}
